### PR TITLE
Fix callling a dynamic sub for object methods

### LINKED ISSUE #3521: Return VCL_SUB from an object method not recognized by VCC
As demonstrated by the patch and VTCs below, an object method returning VCL_SUB is apparently not recognized by VCC as a symbol that may be a target for ``call``. Current vmod_debug shows that it is permitted for a function returning VCL_SUB.

``VRT_call()`` can be invoked from an object method.

Patch:
```
$ git diff
diff --git a/vmod/vmod_debug.c b/vmod/vmod_debug.c
index 25ce2f76e..212b9eeab 100644
--- a/vmod/vmod_debug.c
+++ b/vmod/vmod_debug.c
@@ -1331,3 +1331,62 @@ xyzzy_total_recall(VRT_CTX)
 
        return (wrong);
 }
+
+/*---------------------------------------------------------------------*/
+
+struct VPFX(debug_caller) {
+       unsigned        magic;
+#define DEBUG_CALLER_MAGIC 0xb47f3449
+       VCL_SUB         sub;
+};
+
+VCL_VOID v_matchproto_(td_xyzzy_debug_caller__init)
+xyzzy_caller__init(VRT_CTX, struct VPFX(debug_caller) **callerp,
+                  const char *name, VCL_SUB sub)
+{
+       struct VPFX(debug_caller) *caller;
+
+       CHECK_OBJ_NOTNULL(ctx, VRT_CTX_MAGIC);
+       AN(callerp);
+       AZ(*callerp);
+       AN(name);
+       AN(sub);
+
+       ALLOC_OBJ(caller, DEBUG_CALLER_MAGIC);
+       AN(caller);
+       *callerp = caller;
+       caller->sub = sub;
+}
+
+VCL_VOID v_matchproto_(td_xyzzy_debug_caller__fini)
+xyzzy_caller__fini(struct VPFX(debug_caller) **callerp)
+{
+       struct VPFX(debug_caller) *caller;
+
+       if (callerp == NULL || *callerp == NULL)
+               return;
+       CHECK_OBJ(*callerp, VRT_CTX_MAGIC);
+       caller = *callerp;
+       *callerp = NULL;
+       FREE_OBJ(caller);
+}
+
+VCL_VOID v_matchproto_(td_xyzzy_debug_caller_call)
+xyzzy_caller_call(VRT_CTX, struct VPFX(debug_caller) *caller)
+{
+       CHECK_OBJ_NOTNULL(ctx, VRT_CTX_MAGIC);
+       CHECK_OBJ_NOTNULL(caller, DEBUG_CALLER_MAGIC);
+       AN(caller->sub);
+
+       VRT_call(ctx, caller->sub);
+}
+
+VCL_SUB v_matchproto_(td_xyzzy_debug_caller_sub)
+xyzzy_caller_sub(VRT_CTX, struct VPFX(debug_caller) *caller)
+{
+       CHECK_OBJ_NOTNULL(ctx, VRT_CTX_MAGIC);
+       CHECK_OBJ_NOTNULL(caller, DEBUG_CALLER_MAGIC);
+       AN(caller->sub);
+
+       return (caller->sub);
+}
diff --git a/vmod/vmod_debug.vcc b/vmod/vmod_debug.vcc
index 45fc1fdee..2f709220f 100644
--- a/vmod/vmod_debug.vcc
+++ b/vmod/vmod_debug.vcc
@@ -340,3 +340,9 @@ To test *WRONG* behavior
 $Function SUB total_recall()
 
 To test *WRONG* behavior
+
+$Object caller(SUB)
+
+$Method VOID .call()
+
+$Method SUB .sub()
```

This vtc passes:
```
# looks like -*- vcl -*-

varnishtest "invoke VRT_call() from an object method"

varnish v1 -vcl {
	import debug;
	backend b None;

	sub foo {
		set resp.http.Foo = "Called";
	}

	sub vcl_init {
		new c = debug.caller(foo);
	}

	sub vcl_recv {
		return (synth(200));
	}

	sub vcl_synth {
		c.call();
		return (deliver);
	}
} -start

client c1 {
	txreq
	rxresp
	expect resp.status == 200
	expect resp.http.Foo == "Called"
} -run
```

This one fails:
```
# looks like -*- vcl -*-

varnishtest "return VCL_SUB from an object method"

varnish v1 -vcl {
	import debug;
	backend b None;

	sub foo {
		set resp.http.Foo = "Called";
	}

	sub vcl_init {
		new c = debug.caller(foo);
	}

	sub vcl_recv {
		return (synth(200));
	}

	sub vcl_synth {
		call c.sub();
		return (deliver);
	}
} -start

client c1 {
	txreq
	rxresp
	expect resp.status == 200
	expect resp.http.Foo == "Called"
} -run
```
The error message says that VCC didn't like the method invocation after ``call``:
```
***  v1    CLI RX  106
**** v1    CLI RX|Message from VCC-compiler:
**** v1    CLI RX|Expected ';' got '('
**** v1    CLI RX|(program line 86), at
**** v1    CLI RX|('<vcl.inline>' Line 19 Pos 27)
**** v1    CLI RX|                call c.sub();
**** v1    CLI RX|--------------------------#--
**** v1    CLI RX|
**** v1    CLI RX|Running VCC-compiler failed, exited with 2
**** v1    CLI RX|VCL compilation failed
---- v1    VCL compilation failed expected success
```

### PR DESCRIPTION
**Pull request by nigoroll**
7ec28f1ae91bd39e6e89beb7dffd4248c5054414 did not work with object methods because we need a partial symbol table lookup to identify them, otherwise the symbol kind we find is just SUB for the method's return value.

Fixes #3521

### CODE REVIEW

File: vmod/vmod_debug.c [hunk 1]
```diff
@@ -1331,3 +1331,62 @@ xyzzy_total_recall(VRT_CTX)
...
+}
+
+VCL_VOID v_matchproto_(td_xyzzy_debug_caller__fini)
+xyzzy_caller__fini(struct VPFX(debug_caller) **callerp)
+{
+       struct VPFX(debug_caller) *caller;
+
+       if (callerp == NULL || *callerp == NULL)
+               return;
+       CHECK_OBJ(*callerp, VRT_CTX_MAGIC);
```
Comment (slimhazard) [inline vmod/vmod_debug.c:1368]: As mentioned under the nigoroll account, this should have been DEBUG_CALLER_MAGIC (my bad).

**Review by slimhazard — CHANGES_REQUESTED** [review]

File: vmod/vmod_debug.c (hunk 1 above)
Comment (nigoroll) [reply vmod/vmod_debug.c:1368]: interesting that it did not trip

Comment (nigoroll) [reply vmod/vmod_debug.c:1368]: ah we never discard the vcl in the vtc

**Comment by nigoroll** [comment]
force-pushed
