### PR TITLE
Fix bereq rollback

### LINKED ISSUE #3009: std.rollback() without restart/retry unsafe
If you `std.rollback()` without a restart/retry, workspace gets reset, however, the req and bo still references these locations. This leads to a panic when that workspace gets reused.

VTC:

``` vcl
varnishtest "Rollback without restart/retry is unsafe"

server s1 {
	rxreq
	txresp
} -start

varnish v1 -vcl+backend {
	import std;

	sub vcl_recv {
		set req.http.test = "1";
	}

	sub vcl_backend_fetch {
		unset bereq.http.test;
	}

	sub vcl_backend_response {
		std.rollback(bereq);
		set beresp.http.test = bereq.http.test;
		set beresp.http.workspace = "start overwriting active workspace";
		set beresp.http.workspace = "0123456789012345678901234567890123456789";
		# panic...
	}
} -start

client c1 {
	txreq
	rxresp
	expect resp.status == 200
	expect resp.http.test == "1"
} -run
```

I looked into this, the only safe way to address this is to not reset the workspace on a rollback. Or just docfix this and state you must restart/retry?

### PR DESCRIPTION
**Pull request by nigoroll**
A series of patches to make std.rollback() from vcl_backend_response() safe again.

Fixes #3009 and also pulls straight some more missing error checking.

Please refer to the individual commit messages for more detail.

### CODE REVIEW

File: bin/varnishd/cache/cache_vrt.c [hunk 1]
```diff
@@ -719,12 +719,7 @@ VRT_Rollback(VRT_CTX, VCL_HTTP hp)
 		Req_Rollback(ctx->req);
 	} else if (hp == ctx->http_bereq) {
 		CHECK_OBJ_NOTNULL(ctx->bo, BUSYOBJ_MAGIC);
-		// -> VBO_Rollback ?
-		VCL_TaskLeave(ctx->bo->vcl, ctx->bo->privs);
-		VCL_TaskEnter(ctx->bo->vcl, ctx->bo->privs);
-		HTTP_Clone(ctx->bo->bereq, ctx->bo->bereq0);
-		WS_Reset(ctx->bo->bereq->ws, ctx->bo->ws_bo);
-		WS_Reset(ctx->bo->ws, ctx->bo->ws_bo);
+		Bereq_Rollback(ctx->bo);
```
Comment (Dridi) [inline bin/varnishd/cache/cache_vrt.c]: Rename to VBO_Rollback?

Comment (nigoroll) [reply bin/varnishd/cache/cache_vrt.c]: yeah, names...
When I added the VBO_Rollback comment back in c98edbb0214f6d64b7822def58036cd67e3bdb1d, I would have thought the natural place for the code was `cache_busyobj.c`.
Now that it ended up in for proximity to the reused cleanup function, the natural way would be `VBF_Rollback`, I still thought `Bereq_Rollback` was clearer in analogy to `Bereq_Rollback`.

your choice?

Comment (nigoroll) [reply bin/varnishd/cache/cache_vrt.c]: (damn sorry for all these edits, it's been a long day already)

Comment (Dridi) [reply bin/varnishd/cache/cache_vrt.c]: Calling it `VBO_Something` outside of `cache_busyobj.c` wouldn't be unprecedented, see `VCL_TaskEnter` for example.

Comment (bsdphk) [reply bin/varnishd/cache/cache_vrt.c]: The VBO prefix is for code which works on the internals of busyobj, so to speak things that work on both req.body and beresp.body.

**Comment by nigoroll** [comment]
OK by Dad^H^Hridi via IRC
