### PR TITLE
vbe: Try fetching beresp when sending bereq failed

### LINKED ISSUE #2332: Varnish loses response when backend returns an error during a POST
Varnish may lose the backend response when a backend immediately returns an error when varnish is still sending  a request body.

Example of this situation:

When a POST is received from varnish, and varnish sends the request to an apache backend with 
 a content-length that exceeds LimitRequestBody, apache will immediately return a 413 (Request Entity Too Large).

```
HTTP/1.1 413 Request Entity Too Large
Date: Tue, 23 May 2017 19:51:33 GMT
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>413 Request Entity Too Large</title>
</head><body>
<h1>Request Entity Too Large</h1>
The requested resource<br />/app/foo.php<br />
does not allow request data with POST requests, or the amount of data provided in
the request exceeds the capacity limit.
</body></html>
```

At this point, varnish appears to be in a loop reading/writing the request body from the client to the backend, unaware that the backend has sent an error.

Assuming the complete request body has not been sent, apache will wait until the client closes the connection or it hits the default linger timeout of 30 seconds, which at that point will forcefully close the socket.

The forceful shutting of the socket causes varnish to react with:
```
-        65584 Debug          b "Write error, retval = -1, len = 6, errno = Broken pipe"
-        65584 FetchError     b req.body read error: 32 (Broken pipe)
-        65584 FetchError     b backend write error: 32 (Broken pipe)
```

At this point, varnish returns a backend fetch fail error because of the write failure and never reads the response from the backend, and goes straight to vcl_backend_error.

This is particularly a problem with large POSTs from slow spoon feeding clients. The request body cannot be sent to the backend before the linger timeout (30 seconds).

## Expected Behavior
The error message would be read and returned to the client. Ideally, varnish would immediately detect the backend error preventing the long linger timeout to begin with.

## Current Behavior
Varnish attempts to read the request body until fully read, or an error/timeout occurs even if the backend immediately responds with an error.

## Steps to Reproduce (for bugs)
1. Configure an apache backend LimitRequestBody to a small limit, such as 10485760 
2. Create a 100MB file (dd if=/dev/zero of=largefile.txt bs=1M count=100)
3.  Slowly upload a file to varnish instance with apache backend with slow transfer rate: (curl -v --limit-rate 25K -F foo=@largefile.txt http://varnishendpoint/)

## Your Environment
* Version used: 4.1.6
* Operating System and version: CentOS 7

### PR DESCRIPTION
**Pull request by Dridi**
There is no cancellation mechanism in the middle of an HTTP/1
transaction besides closing the session. If a backend closes
the connection before the end of the bereq delivery, it may
also send a 4XX or 5XX response that could be valuable for the
original client.

In this scenario, we can process the backend response, and we
can use the bereq.send_failed flag to decide what to do about
broken transactions. The beresp.fetch_failed flag can never
be raised in vcl_backend_response but is made available to
enable code sharing with vcl_backend_error as demonstrated in
r02332.

The test case r02332 is a combination of the 3 test cases
from #3686.

There are several things to take into consideration: it is
the responsibility of the backend implementation to raise the
send_failed and fetch_failed flags, if the backend replied
something before closing we shouldn't trigger a timeout, the
connection must not be recycled, and the object must not be
cached.

Fixes #2332
Closes #3686

### CODE REVIEW

**Comment by Algunenano** [comment]
Tested with the most common scenario for us, which is the backend closing the connection due to content length issues and it's working fine and the client receives the 413 code and not a 500.

**Comment by Dridi** [comment]
bugwash summary:

- no `bereq.send_failed` and `beresp.fetch_failed` flags
- no attempt at fetching a beresp unless we sent the bereq headers

I will update the pull request accordingly.

**Comment by Dridi** [comment]
Rebased against master and updated to address bugwash comments.

**Review by nigoroll — COMMENTED** [review]
I am 👍🏽 but feel like I did not review thoroughly enough for clicking _approve_

**Comment by Dridi** [comment]
@Algunenano did you get a chance to test the latest changes?

File: bin/varnishd/cache/cache_backend.c [hunk 1]
```diff
@@ -268,13 +269,15 @@ vbe_dir_gethdrs(VRT_CTX, VCL_BACKEND d)
 	struct pfd *pfd;
 	struct busyobj *bo;
 	struct worker *wrk;
+	enum sess_close sc;
```
Comment (Algunenano) [inline bin/varnishd/cache/cache_backend.c:272]: Doesn't build for me with either GCC or clang:

```
cache/cache_backend.c: In function ‘vbe_dir_gethdrs’
cache/cache_backend.c:272:25: error: storage size of ‘sc’ isn’t known
  272 |         enum sess_close sc;
      |                         ^~
cache/cache_backend.c:272:25: error: unused variable ‘sc’ [-Werror=unused-variable]
```

```
cache/cache_backend.c:272:18: error: variable has incomplete type 'enum sess_close'
        enum sess_close sc;
                        ^
cache/cache_backend.c:272:7: note: forward declaration of 'enum sess_close'
        enum sess_close sc;
             ^
```

Comment (Dridi) [reply bin/varnishd/cache/cache_backend.c]: I just rebased against master to properly solve this conflict, please try again!

**Comment by Algunenano** [comment]
Seems to be working fine.

With master (backend is using Tornado web server):
```
$ curl   -H "Authorization: Bearer p.eyJ1IjogIjhiMjM0NWQ2LWY2YmUtNDE5OC1hMmE2LWMzZDc5ZDVhOTRhNiIsICJpZCI6ICIzMWFhZmVkOC1jNjc0LTQwMzAtOGM1OS0zYmRiOWIyYzE0MGEifQ.144fJO6B_tCzTkI72GynFsjnnXA6-g-3oNg1cB4OH34"   -X POST "http://localhost:6081/v0/datasources?name=stock_prices_1M&mode=append"   --data "@/tmp/stock_prices_1M.csv" -vvv
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:6081...
* Connected to localhost (127.0.0.1) port 6081 (#0)
> POST /v0/datasources?name=stock_prices_1M&mode=append HTTP/1.1
> Host: localhost:6081
> User-Agent: curl/7.81.0
> Accept: */*
> Authorization: Bearer p.eyJ1IjogIjhiMjM0NWQ2LWY2YmUtNDE5OC1hMmE2LWMzZDc5ZDVhOTRhNiIsICJpZCI6ICIzMWFhZmVkOC1jNjc0LTQwMzAtOGM1OS0zYmRiOWIyYzE0MGEifQ.144fJO6B_tCzTkI72GynFsjnnXA6-g-3oNg1cB4OH34
> Content-Length: 84248385
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Backend fetch failed
< Date: Mon, 24 Jan 2022 15:05:34 GMT
< Server: Varnish
< Content-Type: text/html; charset=utf-8
< Retry-After: 5
< Content-Length: 278
< Connection: close
< 
<!DOCTYPE html>
<html>
  <head>
    <title>503 Backend fetch failed</title>
  </head>
  <body>
    <h1>Error 503 Backend fetch failed</h1>
    <p>Backend fetch failed</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 3</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
* we are done reading and this is set to close, stop send
* Closing connection 0
```

With this PR (same backend):
```
$ curl   -H "Authorization: Bearer p.eyJ1IjogIjhiMjM0NWQ2LWY2YmUtNDE5OC1hMmE2LWMzZDc5ZDVhOTRhNiIsICJpZCI6ICIzMWFhZmVkOC1jNjc0LTQwMzAtOGM1OS0zYmRiOWIyYzE0MGEifQ.144fJO6B_tCzTkI72GynFsjnnXA6-g-3oNg1cB4OH34"   -X POST "http://localhost:6081/v0/datasources?name=stock_prices_1M&mode=append"   --data "@/tmp/stock_prices_1M.csv" -vvv
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:6081...
* Connected to localhost (127.0.0.1) port 6081 (#0)
> POST /v0/datasources?name=stock_prices_1M&mode=append HTTP/1.1
> Host: localhost:6081
> User-Agent: curl/7.81.0
> Accept: */*
> Authorization: Bearer p.eyJ1IjogIjhiMjM0NWQ2LWY2YmUtNDE5OC1hMmE2LWMzZDc5ZDVhOTRhNiIsICJpZCI6ICIzMWFhZmVkOC1jNjc0LTQwMzAtOGM1OS0zYmRiOWIyYzE0MGEifQ.144fJO6B_tCzTkI72GynFsjnnXA6-g-3oNg1cB4OH34
> Content-Length: 84248385
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 413 Request Entity Too Large
< Server: TornadoServer/5.1.1
< Content-Type: application/json; charset=UTF-8
< Date: Mon, 24 Jan 2022 15:05:51 GMT
< X-Request-Id: 1edec606-2d17-4bfe-b319-bc672369ab97
< X-Frame-Options: sameorigin
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Authorization, Content-Type, X-Requested-With
< Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
< Access-Control-Max-Age: 86400
< Content-Length: 300
< Connection: keep-alive
< 
* Connection #0 to host localhost left intact
{"error": "The message-body is too large. For requests larger than 8MB, you should use a multipart/form-data request. Use curl -F csv=@file.csv \"http://localhost:8001/v0/datasources\".", "documentation": "/api-reference/datasource-api.html#post--v0-datasources-?", "traceback": ["NoneType: None\n"]}
```

**Comment by bsdphk** [comment]
This looks OK to me.

**Review by nigoroll — APPROVED** [review]

**Comment by nigoroll** [comment]
see #3813 new issues arose.
I thought we could reopen this PR, apparently we can not. Sorry.

**Comment by Dridi** [comment]
A few clicks later, #3814.
