### PR TITLE
Ban parser: don't accept object name prefixes

### LINKED ISSUE #3962: ban parser accepts object name prefixes
### Expected Behavior

this should fail: `varnishadm ban 'req.urlXX ~ "foobarbazzz"'`

### Current Behavior

it doesn't:

```
$ varnishadm ban 'req.urlXX ~ "foobarbazzz"'
$ varnishadm ban.list | head -2
Present bans:
1690455463.581419  1513 -  req.url ~ foobarbazzz
```

### Possible Solution

_No response_

### Steps to Reproduce (for bugs)

_No response_

### Context

n/a

### Varnish Cache version

_No response_

### Operating system

_No response_

### Source of binary packages used (if any)

_No response_

### PR DESCRIPTION
**Pull request by walid-git**
Fixes #3962

### CODE REVIEW

**Comment by walid-git** [comment]
Reworked the PR to also avoid bans on "req.ur".
Also added 4f17a68ce6406a92e7316eee0e07725709dcfa0d to prevent ban expressions with empty http header names that can lead to a panic (see [my comment](https://github.com/varnishcache/varnish-cache/issues/3962#issuecomment-1668222750) for details)

**Comment by bsdphk** [comment]
Looks good.

**Review by nigoroll — APPROVED** [review]
Thank you @walid-git

File: bin/varnishd/cache/cache_ban_build.c [hunk 1]
```diff
@@ -246,7 +246,8 @@ BAN_AddTest(struct ban_proto *bp,
 		return (bp->err);
 
 	for (pv = pvars; pv->name != NULL; pv++)
-		if (!strncmp(a1, pv->name, strlen(pv->name)))
+		if ((!(pv->flag & BANS_FLAG_HTTP) && !strcmp(a1, pv->name))
+			|| (pv->flag & BANS_FLAG_HTTP && !strncmp(a1, pv->name, strlen(pv->name))))
 			break;
```
Comment (Dridi) [inline bin/varnishd/cache/cache_ban_build.c:251]: Maybe decompose the loop to make it more readable?

```c
for (pv = pvars; pv->name != NULL; pv++) {
        is_http = pv->flag & BANS_FLAG_HTTP;
        if (!is_http && !strcmp())
            break;
        if (is_http && !strncmp())
            break;
}
```

Otherwise there's probably a line too long, the `||` should be on the previous line and this is the wrong indentation for the if continuation.

Also, this is lacking a test case.

File: bin/varnishtest/tests/r03962.vtc [hunk 2]
```diff
@@ -0,0 +1,13 @@
+varnishtest "ban expression object name prefixes"
```
Comment (Dridi) [inline bin/varnishtest/tests/r03962.vtc:1]: Please squash into first commit.

File: bin/varnishd/cache/cache_ban_build.c [hunk 3]
```diff
@@ -258,6 +258,9 @@ BAN_AddTest(struct ban_proto *bp,
 
 	VSB_putc(bp->vsb, pv->tag);
 	if (pv->flag & BANS_FLAG_HTTP) {
+		if (strlen(a1 + strlen(pv->name)) < 1)
+			return (ban_error(bp,
+			    "An HTTP header name must be specified after \"%s\"", pv->name));
```
Comment (Dridi) [inline bin/varnishd/cache/cache_ban_build.c:263]:
```c
"Missing header name: '%s'"
```

**Review by Dridi — CHANGES_REQUESTED** [review]
A thought occurred to me, VCL supports "non symbolic" header names with the following syntax:

```vcl
req.http."valid.header.name"
```

But I don't think the ban parser learned about these.

**Comment by walid-git** [comment]
Addressed @Dridi's comments. Also added changelog

> A thought occurred to me, VCL supports "non symbolic" header names with the following syntax:
> ```
> req.http."valid.header.name"
> ```
> But I don't think the ban parser learned about these.

This does't seem to be directly related to this issue, we should probably handle that separately

**Review by Dridi — APPROVED** [review]
