### PR TITLE
[vnum] more lenient test

### LINKED ISSUE #3697: vnum_c_test fails on alpine x_86
while trying to build packages for `7.0.0` I hit this:
```
==================================================
   Varnish 7.0.0: lib/libvarnish/test-suite.log
==================================================
# TOTAL: 6
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
.. contents:: :depth: 2
FAIL: vnum_c_test
=================
./vnum_c_test: VNUM_Duration() wrong, 31556908.800 delta = 8.658390e-10
FAIL vnum_c_test (exit status: 1)
```

This is on `alpine`, so using `muslc`, and the arch is `x86`, full log here: https://gitlab.alpinelinux.org/gquintard/aports/-/jobs/487996

### PR DESCRIPTION
**Pull request by gquintard**
fixes #3697

@Dridi, I know we discussed `VTIM_EPSILON` but `VNUM_EPSILON` kept things in vnum land, and we use it to test `VNUM_duration`, so it made sense?

### CODE REVIEW

File: include/vnum.h [hunk 1]
```diff
@@ -31,6 +31,7 @@
  */
 
 /* from libvarnish/vnum.c */
+#define VNUM_EPSILON 1e-9
```
Comment (Dridi) [inline include/vnum.h:34]: Maybe something like `#define VNUM_EPSILON (1e-9d)` ?

**Review by Dridi — CHANGES_REQUESTED** [review]
Of course, `VNUM_EPSILON` makes more sense.

File: include/vnum.h (hunk 1 above)
Comment (gquintard) [reply include/vnum.h]: there you go
