### PR TITLE
VCP: Fix a race that leads to a panic when destroying connection pools 

### LINKED ISSUE #4260: Panic at bin/varnishd/cache/cache_lck.c:314 pthread_mutex_destroy(&ilck->mtx) failed
### Expected Behavior

No panic

### Current Behavior

```
***  v1    debug|Error: Child (41061) not responding to CLI, killed it.
***  v1    debug|Error: Unexpected reply from ping: 400 CLI communication error (hdr)
***  v1    debug|Error: Child (41061) died signal=6
***  v1    debug|Error: Child (41061) Panic at: Wed, 05 Feb 2025 09:18:03 GMT
***  v1    debug|Wrong turn at ../../../../bin/varnishd/cache/cache_lck.c:314:
***  v1    debug|pthread_mutex_destroy(&ilck->mtx) failed
***  v1    debug|version = varnish-trunk revision b0dcf6b901413d78f93d2aad9f92b0327d02c466, vrt api = 20.1
***  v1    debug|ident = Linux,6.8.0-1021-aws,x86_64,-jnone,-sdefault,-sdefault,-hcritbit,epoll
***  v1    debug|now = 4580.407738 (mono), 1738747083.187305 (real)
***  v1    debug|Backtrace:
***  v1    debug|  ip=0x4fdb14 sp=0x7ffc73b414c0 <VBT_format+0x2c>
***  v1    debug|  ip=0x457331 sp=0x7ffc73b414e0 <pan_backtrace+0x3a>
***  v1    debug|  ip=0x45787c sp=0x7ffc73b41500 <pan_ic+0x32e>
***  v1    debug|  ip=0x4fc9fd sp=0x7ffc73b41610 <VAS_Fail+0x53>
***  v1    debug|  ip=0x4500ae sp=0x7ffc73b41650 <Lck_Delete+0x11b>
***  v1    debug|  ip=0x42e641 sp=0x7ffc73b41690 <vcp_destroy+0xfe>
***  v1    debug|  ip=0x42eab0 sp=0x7ffc73b416c0 <VCP_RelPoll+0x14d>
***  v1    debug|  ip=0x42cf28 sp=0x7ffc73b41700 <cli_cb_before+0x97>
***  v1    debug|  ip=0x4fed68 sp=0x7ffc73b41730 <cls_exec+0x1b7>
***  v1    debug|  ip=0x4ff3b3 sp=0x7ffc73b41790 <cls_feed+0x409>
***  v1    debug|  ip=0x50058f sp=0x7ffc73b41810 <VCLS_Poll+0x2c5>
***  v1    debug|  ip=0x42d0a3 sp=0x7ffc73b43870 <CLI_Run+0xc2>
***  v1    debug|  ip=0x4512ce sp=0x7ffc73b43890 <child_main+0x3c5>
***  v1    debug|  ip=0x4a79ac sp=0x7ffc73b438e0 <mgt_launch_child+0x403>
***  v1    debug|  ip=0x4a88bc sp=0x7ffc73b43960 <mch_cli_server_start+0x3a>
***  v1    debug|  ip=0x4feba3 sp=0x7ffc73b439a0 <cls_dispatch+0x33c>
***  v1    debug|  ip=0x4fee55 sp=0x7ffc73b439e0 <cls_exec+0x2a4>
***  v1    debug|  ip=0x4ff3b3 sp=0x7ffc73b43a40 <cls_feed+0x409>
***  v1    debug|  ip=0x50058f sp=0x7ffc73b43ac0 <VCLS_Poll+0x2c5>
***  v1    debug|  ip=0x4a9819 sp=0x7ffc73b45b20 <mgt_cli_callback2+0x2e>
***  v1    debug|  ip=0x502ee9 sp=0x7ffc73b45b50 <VEV_Once+0x47e>
***  v1    debug|  ip=0x502876 sp=0x7ffc73b45ba0 <VEV_Loop+0xba>
***  v1    debug|  ip=0x4afce1 sp=0x7ffc73b45bd0 <main+0x19ce>
***  v1    debug|  ip=0x7f0efc48b7e5 sp=0x7ffc73b45db0 <__libc_start_main+0xe5>
***  v1    debug|  ip=0x4181ae sp=0x7ffc73b45e60 <_start+0x2e>
***  v1    debug|errno = 16 (Device or resource busy)
***  v1    debug|argv = {
***  v1    debug|  [0] = \"varnishd\",
***  v1    debug|  [1] = \"-d\",
***  v1    debug|  [2] = \"-n\",
***  v1    debug|  [3] = \"/tmp/vtc.40943.0d83a9ae/v1\",
***  v1    debug|  [4] = \"-i\",
***  v1    debug|  [5] = \"v1\",
***  v1    debug|  [6] = \"-l\",
***  v1    debug|  [7] = \"2m\",
***  v1    debug|  [8] = \"-p\",
***  v1    debug|  [9] = \"auto_restart=off\",
***  v1    debug|  [10] = \"-p\",
***  v1    debug|  [11] = \"syslog_cli_traffic=off\",
***  v1    debug|  [12] = \"-p\",
***  v1    debug|  [13] = \"thread_pool_min=10\",
***  v1    debug|  [14] = \"-p\",
***  v1    debug|  [15] = \"debug=+vtc_mode\",
***  v1    debug|  [16] = \"-p\",
***  v1    debug|  [17] = \"vsl_mask=+Debug,+H2RxHdr,+H2RxBody\",
***  v1    debug|  [18] = \"-p\",
***  v1    debug|  [19] = \"h2_initial_window_size=1m\",
***  v1    debug|  [20] = \"-p\",
***  v1    debug|  [21] = \"h2_rx_window_low_water=64k\",
***  v1    debug|  [22] = \"-a\",
***  v1    debug|  [23] = \"127.0.0.1:0\",
***  v1    debug|  [24] = \"-M\",
***  v1    debug|  [25] = \"127.0.0.1 41177\",
***  v1    debug|  [26] = \"-P\",
***  v1    debug|  [27] = \"/tmp/vtc.40943.0d83a9ae/v1/varnishd.pid\",
***  v1    debug|  [28] = \"-p\",
***  v1    debug|  [29] = \"vmod_path=/workspace/varnish-trunk/_build/sub/vmod/.libs\",
***  v1    debug|}
***  v1    debug|pthread.self = 0x7f0efdb26fc0
***  v1    debug|pthread.name = (cache-main)
***  v1    debug|pthread.attr = {
***  v1    debug|  guard = 0,
***  v1    debug|  stack_bottom = 0x7ffc73350000,
***  v1    debug|  stack_top = 0x7ffc73b46000,
***  v1    debug|  stack_size = 8347648,
***  v1    debug|}
***  v1    debug|thr.req = NULL
***  v1    debug|thr.busyobj = NULL
***  v1    debug|thr.worker = NULL
***  v1    debug|vmods = {
***  v1    debug|},
***  v1    debug|pools = {
***  v1    debug|  pool = 0x7f0ef9000000 {
***  v1    debug|    nidle = 9,
***  v1    debug|    nthr = 10,
***  v1    debug|    lqueue = 0
***  v1    debug|  },
***  v1    debug|  pool = 0x7f0ef9000640 {
***  v1    debug|    nidle = 9,
***  v1    debug|    nthr = 10,
***  v1    debug|    lqueue = 0
***  v1    debug|  },
***  v1    debug|},
***  v1    debug|
***  v1    debug|
***  v1    debug|Debug: Child cleanup complete
```

### Possible Solution

_No response_

### Steps to Reproduce (for bugs)

Triggered by tests/b00083.vtc

### Context

Found on CCI job https://app.circleci.com/pipelines/github/varnishcache/varnish-cache/6664/workflows/60f34ff9-6b3f-4a00-b950-06e5d972a01b/jobs/86270

Possibly related to a recent change in https://github.com/varnishcache/varnish-cache/pull/4198

### Varnish Cache version

_No response_

### Operating system

_No response_

### Source of binary packages used (if any)

_No response_

### PR DESCRIPTION
**Pull request by walid-git**
This was recently introduced in #4198 and observed on a CCI job failure. The race happens between the waiter thread and the CLI thread, a stack trace of both threads during the panic can be found in https://github.com/varnishcache/varnish-cache/issues/4260#issuecomment-2639365725.

The race is caused by the fact that we read `cp->n_kill` without holding the `cp` mutex in `VCP_RelPoll()`:
- The waiter thread (holding the mutex) sets `n_kill` to 0 and is then interrupted before being able to release the lock.
- The CLI thread reads `cp->n_kill` and calls `vcp_destroy()` on the connection pool, which in turn calls `Lck_Delete` on a lock still being hold by the waiter thread. 

Another occurrence of reading `n_kill` without holding the mutex  in `VCP_Rel` (which could potentially lead to a similar panic) was also addressed.

Refs #4198
Fixes #4260

### CODE REVIEW

File: bin/varnishd/cache/cache_conn_pool.c [hunk 1]
```diff
@@ -303,8 +304,12 @@ VCP_RelPoll(void)
 
 	VRBT_FOREACH_SAFE(cp, vrb, &dead, cp2) {
 		CHECK_OBJ_NOTNULL(cp, CONN_POOL_MAGIC);
-		if (cp->n_kill > 0)
+		Lck_Lock(&cp->mtx);
```
Comment (nigoroll) [inline bin/varnishd/cache/cache_conn_pool.c:307]: Very minor polish suggestion (pseudo-C, not tested):
```c
Lck_Lock(&cp->mtx);
n = cp->n_kill;
Lck_Unlock(&cp->mtx);
if (n > 0)
    continue;
VRBT_REMOVE(....
```

**Review by nigoroll — APPROVED** [review]

File: bin/varnishd/cache/cache_conn_pool.c [hunk 2]
```diff
@@ -270,11 +270,12 @@ VCP_Rel(struct conn_pool **cpp)
 		(void)shutdown(pfd->fd, SHUT_RDWR);
 		cp->n_kill++;
 	}
-	Lck_Unlock(&cp->mtx);
 	if (cp->n_kill == 0) {
+		Lck_Unlock(&cp->mtx);
```
Comment (nigoroll) [inline bin/varnishd/cache/cache_conn_pool.c:274]: ah and the very minor polish suggestion applies here as well

**Review by nigoroll — APPROVED** [review]

**Comment by nigoroll** [comment]
I think we do not need another review from phk, as this is simple enough.
