### PR TITLE
Master exprace

### LINKED ISSUE #2999: Assert error in EXP_Insert(), cache/cache_expire.c line 151: Condition((oc->flags & OC_F_DYING) == 0) not true.
I got this panic from current master:

<details>
<summary>Show panic</summary>

```
**** top   1.2 shell_out|Assert error in EXP_Insert(), cache/cache_expire.c line 151:
**** top   1.2 shell_out|  Condition((oc->flags & OC_F_DYING) == 0) not true.
**** top   1.2 shell_out|version = varnish-trunk revision a2ccbc37a460de541ce93f18112185e34b82abe9, vrt api = 9.0
**** top   1.2 shell_out|ident = Linux,5.0.13-300.fc30.x86_64,x86_64,-jnone,-sdefault,-sdefault,-hcritbit,epoll
**** top   1.2 shell_out|now = 132793.201615 (mono), 1557925815.291696 (real)
**** top   1.2 shell_out|Backtrace:                        
**** top   1.2 shell_out|  0x456720: varnishd() [0x456720]                
**** top   1.2 shell_out|  0x4564ea: varnishd() [0x4564ea]
**** top   1.2 shell_out|  0x511aa1: varnishd(VAS_Fail+0x51) [0x511aa1]
**** top   1.2 shell_out|  0x4346a0: varnishd(EXP_Insert+0x220) [0x4346a0]
**** top   1.2 shell_out|  0x444267: varnishd(HSH_Unbusy+0x587) [0x444267]
**** top   1.2 shell_out|  0x4394f2: varnishd() [0x4394f2]
**** top   1.2 shell_out|  0x436cf6: varnishd() [0x436cf6]    
**** top   1.2 shell_out|  0x493453: varnishd() [0x493453]                         
**** top   1.2 shell_out|  0x492c82: varnishd() [0x492c82]                               
**** top   1.2 shell_out|  0x4929cb: varnishd() [0x4929cb] 
**** top   1.2 shell_out|thread = (cache-worker)  
**** top   1.2 shell_out|pthread.attr = {                                               
**** top   1.2 shell_out|  guard = 4096,                       
**** top   1.2 shell_out|  stack_bottom = 0x7fb21a4ff000,                   
**** top   1.2 shell_out|  stack_top = 0x7fb21a50d000,      
**** top   1.2 shell_out|  stack_size = 57344,                                                                    
**** top   1.2 shell_out|}                              
**** top   1.2 shell_out|thr.req = (nil) {                                        
**** top   1.2 shell_out|},                  
**** top   1.2 shell_out|thr.busyobj = 0x7fb20d4aaaa0 {
**** top   1.2 shell_out|  end = 0x7fb20d4baa80,                 
**** top   1.2 shell_out|  retries = 0,                  
**** top   1.2 shell_out|  sp = 0x7fb20ec18820 {                       
**** top   1.2 shell_out|    fd = 56, vxid = 2064430,
**** top   1.2 shell_out|    t_open = 1557925815.279029,
**** top   1.2 shell_out|    t_idle = 1557925815.289282,
**** top   1.2 shell_out|    ws = 0x7fb20ec18860 {
**** top   1.2 shell_out|      id = \"ses\",
**** top   1.2 shell_out|      {s, f, r, e} = {0x7fb20ec188a0, +104, (nil), +344},
**** top   1.2 shell_out|    },
**** top   1.2 shell_out|    transport = H2 {
**** top   1.2 shell_out|      streams {
**** top   1.2 shell_out|        0x00000000 idle
**** top   1.2 shell_out|        0x00000011 c-rem
**** top   1.2 shell_out|      }
**** top   1.2 shell_out|    }
**** top   1.2 shell_out|    client = 127.0.0.1 40828 127.0.0.1:38225,
**** top   1.2 shell_out|  },
**** top   1.2 shell_out|  worker = 0x7fb21a50a5c0 {
**** top   1.2 shell_out|    ws = 0x7fb21a50a668 {
**** top   1.2 shell_out|      id = \"wrk\",
**** top   1.2 shell_out|      {s, f, r, e} = {0x7fb21a509bd0, +0, (nil), +2040},
**** top   1.2 shell_out|    },
**** top   1.2 shell_out|    VCL::method = BACKEND_RESPONSE,
**** top   1.2 shell_out|    VCL::return = deliver,
**** top   1.2 shell_out|    VCL::methods = {BACKEND_FETCH, BACKEND_RESPONSE},
**** top   1.2 shell_out|  },
**** top   1.2 shell_out|  vfc = 0x7fb20d4ac990 {
**** top   1.2 shell_out|    failed = 0,
**** top   1.2 shell_out|    req = 0x7fb20d4ab0a0,
**** top   1.2 shell_out|    resp = 0x7fb20d4ab518,
**** top   1.2 shell_out|    wrk = 0x7fb21a50a5c0,
**** top   1.2 shell_out|    oc = 0x7fb2115266c0,
**** top   1.2 shell_out|    filters = {
**** top   1.2 shell_out|      V1F_STRAIGHT = 0x7fb20d4accd0 {
**** top   1.2 shell_out|        priv1 = 0x7fb20d4aca98,
**** top   1.2 shell_out|        priv2 = 229,
**** top   1.2 shell_out|        closed = 0
**** top   1.2 shell_out|      },
**** top   1.2 shell_out|    },
**** top   1.2 shell_out|    obj_flags = 0x0,
**** top   1.2 shell_out|  },
**** top   1.2 shell_out|  filter_list = \"\",
**** top   1.2 shell_out|  ws = 0x7fb20d4aaae0 {
**** top   1.2 shell_out|    id = \"bo\",
**** top   1.2 shell_out|    {s, f, r, e} = {0x7fb20d4ac9d8, +832, (nil), +57504},
**** top   1.2 shell_out|  },
**** top   1.2 shell_out|  ws_bo = 0x7fb20d4aca80,
**** top   1.2 shell_out|  http[bereq] = 0x7fb20d4ab0a0 {
**** top   1.2 shell_out|    ws = 0x7fb20d4aaae0 {
**** top   1.2 shell_out|      [Already dumped, see above]
**** top   1.2 shell_out|    },
**** top   1.2 shell_out|    hdrs {
**** top   1.2 shell_out|      \"GET\",
**** top   1.2 shell_out|      \"/\",
**** top   1.2 shell_out|      \"HTTP/1.1\",
**** top   1.2 shell_out|      \"scheme: http\",
**** top   1.2 shell_out|      \"host: 127.0.0.1:38225\",
**** top   1.2 shell_out|      \"user-agent: h2load nghttp2/1.38.0\",
**** top   1.2 shell_out|      \"X-Forwarded-For: 127.0.0.1\",
**** top   1.2 shell_out|      \"Accept-Encoding: gzip\",
**** top   1.2 shell_out|      \"X-Varnish: 2261038\",
**** top   1.2 shell_out|    },
**** top   1.2 shell_out|  },
**** top   1.2 shell_out|  http[beresp] = 0x7fb20d4ab518 {
**** top   1.2 shell_out|    ws = 0x7fb20d4aaae0 {
**** top   1.2 shell_out|      [Already dumped, see above]
**** top   1.2 shell_out|    },
**** top   1.2 shell_out|    hdrs {
**** top   1.2 shell_out|      \"HTTP/1.1\",
**** top   1.2 shell_out|      \"200\",
**** top   1.2 shell_out|      \"OK\",
**** top   1.2 shell_out|      \"Date: Wed, 15 May 2019 13:10:15 GMT\",
**** top   1.2 shell_out|      \"Server: Varnish\",
**** top   1.2 shell_out|      \"X-Varnish: 425987\",
**** top   1.2 shell_out|      \"Cache-Control: no-cache\",
**** top   1.2 shell_out|      \"Content-Type: text/html; charset=utf-8\",
**** top   1.2 shell_out|      \"Retry-After: 5\",
**** top   1.2 shell_out|      \"Content-Length: 229\",
**** top   1.2 shell_out|      \"Accept-Ranges: bytes\",
**** top   1.2 shell_out|      \"Connection: keep-alive\",
**** top   1.2 shell_out|    },
**** top   1.2 shell_out|  },
**** top   1.2 shell_out|  objcore[stale_oc] = 0x7fb211526780 {
**** top   1.2 shell_out|    refcnt = 2,
**** top   1.2 shell_out|    flags = {hfm, abandon, dying},
**** top   1.2 shell_out|    exp_flags = {},
**** top   1.2 shell_out|    exp = {1557925815.289763, 120.000000, 10.000000, 0.000000},
**** top   1.2 shell_out|    objhead = 0x7fb20e81e000,
**** top   1.2 shell_out|    stevedore = 0x7fb22122a0c0 (malloc Transient) {
**** top   1.2 shell_out|      Simple = 0x7fb216870600,
**** top   1.2 shell_out|      Obj = 0x7fb21680a0d8 {priv=0x7fb21680a0d0, ptr=0x7fb216870600, len=336, space=336},
**** top   1.2 shell_out|      LEN = 0x00000000000000e5,
**** top   1.2 shell_out|      VXID = 0x001e0036,
**** top   1.2 shell_out|      FLAGS = 0x00,
**** top   1.2 shell_out|      GZIPBITS = 0x0...0,
**** top   1.2 shell_out|      LASTMODIFIED = 0x41d73703edc00000,
**** top   1.2 shell_out|      VARY = {len=0, ptr=(nil)},
**** top   1.2 shell_out|      HEADERS = {len=216, ptr=0x7fb216870678},
**** top   1.2 shell_out|    },
**** top   1.2 shell_out|  },
**** top   1.2 shell_out|  objcore[fetch] = 0x7fb2115266c0 {                                                                                                                         [45/1877]
**** top   1.2 shell_out|    refcnt = 3,
**** top   1.2 shell_out|    flags = {hfm, dying},
**** top   1.2 shell_out|    exp_flags = {},
**** top   1.2 shell_out|    boc = 0x7fb20e41d940 {
**** top   1.2 shell_out|      refcnt = 2,
**** top   1.2 shell_out|      state = prep_stream,
**** top   1.2 shell_out|      vary = (nil),
**** top   1.2 shell_out|      stevedore_priv = (nil),
**** top   1.2 shell_out|    },
**** top   1.2 shell_out|    exp = {1557925815.290781, 120.000000, 10.000000, 0.000000},
**** top   1.2 shell_out|    objhead = 0x7fb20e81e000,
**** top   1.2 shell_out|    stevedore = 0x7fb22122a0c0 (malloc Transient) {
**** top   1.2 shell_out|      Simple = 0x7fb20fab2700,
**** top   1.2 shell_out|      Obj = 0x7fb2192080a8 {priv=0x7fb2192080a0, ptr=0x7fb20fab2700, len=336, space=336},
**** top   1.2 shell_out|      LEN = 0x0...0,
**** top   1.2 shell_out|      VXID = 0x0022802e,
**** top   1.2 shell_out|      FLAGS = 0x00,
**** top   1.2 shell_out|      GZIPBITS = 0x0...0,
**** top   1.2 shell_out|      LASTMODIFIED = 0x41d73703edc00000,
**** top   1.2 shell_out|      VARY = {len=0, ptr=(nil)},
**** top   1.2 shell_out|      HEADERS = {len=216, ptr=0x7fb20fab2778},
**** top   1.2 shell_out|    },
**** top   1.2 shell_out|  },
**** top   1.2 shell_out|  http_conn = 0x7fb20d4aca98 {
**** top   1.2 shell_out|    fd = 41 (@0x7fb210ed87f4),
**** top   1.2 shell_out|    doclose = NULL,
**** top   1.2 shell_out|    ws = 0x7fb20d4aaae0 {
**** top   1.2 shell_out|      [Already dumped, see above]
**** top   1.2 shell_out|    },
**** top   1.2 shell_out|    {rxbuf_b, rxbuf_e} = {0x7fb20d4acaf8, 0x7fb20d4acbe8},
**** top   1.2 shell_out|    {pipeline_b, pipeline_e} = {0x7fb20d4acbe8, 0x7fb20d4acccd},
**** top   1.2 shell_out|    content_length = 229,
**** top   1.2 shell_out|    body_status = length,
**** top   1.2 shell_out|    first_byte_timeout = 60.000000,
**** top   1.2 shell_out|    between_bytes_timeout = 60.000000,
**** top   1.2 shell_out|  },
**** top   1.2 shell_out|  flags = {do_stream, uncacheable},
**** top   1.2 shell_out|  director_req = 0x7fb221213820 {
**** top   1.2 shell_out|    cli_name = boot.be,
**** top   1.2 shell_out|    admin_health = healthy, changed = 1557925815.090408,
**** top   1.2 shell_out|    type = backend {
**** top   1.2 shell_out|      ipv4 = 127.0.0.1,
**** top   1.2 shell_out|      port = 45357,
**** top   1.2 shell_out|      hosthdr = 127.0.0.1 45357,
**** top   1.2 shell_out|      n_conn = 9,
**** top   1.2 shell_out|    },
**** top   1.2 shell_out|  },
**** top   1.2 shell_out|  director_resp = director_req,
**** top   1.2 shell_out|  vcl = {
**** top   1.2 shell_out|    name = \"boot\",
**** top   1.2 shell_out|    busy = 75,
**** top   1.2 shell_out|    discard = 0,
**** top   1.2 shell_out|    state = auto,
**** top   1.2 shell_out|    temp = warm,
**** top   1.2 shell_out|    conf = {
**** top   1.2 shell_out|      syntax = \"40\",
**** top   1.2 shell_out|      srcname = {
**** top   1.2 shell_out|        \"/tmp/vtc.25611.0fe4a705/proxy.vcl\",
**** top   1.2 shell_out|        \"Builtin\",
**** top   1.2 shell_out|      },
**** top   1.2 shell_out|    },
**** top   1.2 shell_out|  },
**** top   1.2 shell_out|},
**** top   1.2 shell_out|vmods = {
**** top   1.2 shell_out|},
```

</details>

With the following test case:
<details>
<summary>Show test case</summary>

```
varnishtest "Assert error in EXP_Insert()"

shell {
cat >backend.vcl <<EOF
vcl 4.0;

backend dummy {
	.host = "${bad_backend}";
}

sub vcl_recv {
	return (synth(200));
}

sub vcl_synth {
	set resp.http.Cache-Control = "no-cache";
}
EOF
}

process p_backend {
	varnishd -F -n ${tmpdir}/backend -f ${tmpdir}/backend.vcl -a 127.0.0.1:0
} -start

shell {
varnishadm -n ${tmpdir}/backend debug.listen_address >backend.sock

cat >proxy.vcl <<EOF
vcl 4.0;

backend be {
	.host = "$(cat backend.sock)";
}
EOF
}

process p_proxy {
	varnishd -F -n ${tmpdir}/proxy -f ${tmpdir}/proxy.vcl -a 127.0.0.1:0 \
		-p feature=+http2 -p thread_pool_min=40 -p thread_pool_max=40 \
		-p thread_pool_watchdog=0.1
} -start

shell {
varnishadm -n ${tmpdir}/proxy debug.listen_address | tr ' ' : >proxy.sock

h2load -c 100 -n 2000 http://$(cat proxy.sock)/ || :

varnishadm -n ${tmpdir}/proxy panic.show && exit 1

# process -kill sends a signal to all processes...
kill ${p_backend_pid}
kill ${p_proxy_pid}
}

process p_backend -wait
process p_proxy -wait
```

</details>

I run it with `-n 100` and eventually it fails with this panic. I wasn't able to fail the test with any other outcome.

### PR DESCRIPTION
**Pull request by mbgrydeland**
This patch set is to fix #2999

### CODE REVIEW

File: bin/varnishd/cache/cache_expire.c [hunk 1]
```diff
@@ -105,25 +105,45 @@ exp_mail_it(struct objcore *oc, uint8_t cmds)
 {
 	CHECK_OBJ_NOTNULL(oc, OBJCORE_MAGIC);
 	assert(oc->refcnt > 0);
+	AZ(cmds & OC_EF_REFD);
 
-	Lck_Lock(&exphdl->mtx);
-	if ((cmds | oc->exp_flags) & OC_EF_REFD) {
+	Lck_AssertHeld(&exphdl->mtx);
+
+	if (oc->exp_flags & OC_EF_REFD) {
```
Comment (nigoroll) [inline bin/varnishd/cache/cache_expire.c]: It seems this is already guaranteed except for the call from `EXP_Rearm()`.

Would it make sense to turn this into `AN(oc->exp_flags & OC_EF_REFD)` and have `EXP_Rearm()` only call `exp_mail_it()` if OC_EF_REFD is set?

Note: I understand that we need to operate on `OC_EF_NEW` under the lock, but I do not see how we could race for `OC_EF_REFD` ?

Comment (mbgrydeland) [reply bin/varnishd/cache/cache_expire.c]: It is also a concern from EXP_Remove. OC_EF_REFD is first tested without the lock in both EXP_Remove and EXP_Rearm., because it can not be gained once lost, and early return is done if the flag is missing. That way the mutex is not needed for objects not on expiry, e.g. transient and passes. But if it was found before getting the mutex, it needs to be tested again after getting the mutex. exp_mail_it handles that for both EXP_Rearm and EXP_Remove.

Comment (nigoroll) [reply bin/varnishd/cache/cache_expire.c]: Thank you, I see it now.
